### ISSUE TITLE
Rendering issues with 9-slice scale on OpenFL 4.0 Windows target

### ISSUE THREAD

**Issue by datee** [haxeui/haxeui-openfl#2]
9-slice scaling of background images produces "cuts" in the graphics. 
Tested on Windows, Flash and HTML5. 
Seems to only happen on the windows target using OpenFL 4.0.
![issue](https://cloud.githubusercontent.com/assets/1677550/16949534/9cfd11d6-4dbb-11e6-99ce-9eee3763cfc9.jpg)

FD testproject to reproduce the issue here:
https://www.sendspace.com/file/uaob2g

**Comment by ianharrigan** [comment]
Fantastic, thanks for the test app! Really helps knocking these things off really quickly when i get a spare few minutes. Ive attached the .zip here for completeness and so it doesnt get deleted from that hosting site.

Cheers,
Ian

[HaxeUI2_winFL4_9slice_issue.zip](https://github.com/haxeui/haxeui-openfl/files/371412/HaxeUI2_winFL4_9slice_issue.zip)

**Comment by ianharrigan** [comment]
It seems like this might be a regression from `3.6.1` to `4.0.0` - i tried with git version and app crashed. Tried with `3.6.1` and it worked and looked fine , tried with `4.0.0` and app didnt crash, but slicing was wrong as per image you supplied.

**Comment by datee** [comment]
So, is this something the openfl team needs to fix then? Its the same for openFL 4.0.3..  Also there are some issues with 3.6.1 .. backgrounds with 9-slice scaling inside a scrollview dont follow the scrolling, but is static while the rest of the content scrolls...

**Comment by ianharrigan** [comment]
Yeah, i think it might be openfl related. Can you maybe open another issue about the scrolling?

**Comment by sourceskyboxer** [comment]
Try to use OpenFL 4.1.0 and It is sometimes if I create example:

> 		var myButton:Button = new Button();
> 		myButton.x = 10;
> 		myButton.y = 270;
> 		myButton.text = "Test Window";
> 		myButton.onClick = function(e) {
> 			
> 			var _win:Window = new Window({y:200, x:400, width:400, height:300, title:"Example 2 Window"});
> 			var _background:Sprite = new Sprite();
> 			_background.graphics.beginFill(0xFF8800, 1);
> 			_background.graphics.drawRect(_background.x, _background.y, _win.width, _win.height);
> 			_background.graphics.endFill();
> 			_win.stage.addChild(_background); // <- Alway crashes app if you use stage.addChild();
> 			if (_win.id < 0)
> 			{
> 				_app.createWindow(_win);
> 			}
> 		}
> 		Screen.instance.addComponent(myButton);
Why do i not understand since 3.0.0 Lime hasn't problem with multi windows .
But where is alwayfront or ToolWindow or NormalWindowl or SizableWindow.

PS: Don't use SDL Window from lime I saw it. Why do you not use winapi ( default windows coding,) , cocoa ( Mac OS X ) and Gnome/KDE ( Linux ) Or simple use standard frameworks like GTK UI or QT UI?

I hooe next version for Lime Graphic User Interface.

**Comment by ianharrigan** [comment]
This is unrelated to this issue, can you open another issue if you are opening a new issue, that is unrelated?

Thanks.
Ian

**Comment by ianharrigan** [comment]
Can you retest this and close if its not still an issue? I cant reproduce it anymore. 

Cheers,
Ian

**Comment by datee** [comment]
Great. Did retesting, it seems to have been fixed!
