### ISSUE TITLE
"Screen.instance.messageDialog" bug or improper use? pls help

### ISSUE THREAD

**Issue by Helgiii** [haxeui/haxeui-openfl#21]
Openup & close 1 dialog, then open another and there's the bug..
And it looks like this, a new dimmer appears but no dialog or controls are seen.. BUT
if you put mouse cursor right where the OK btn should have been mouse cursor changes to HAND and I can click and close the dialog, although nothing is seen except for the dimmer

## Test app / minimal test case
```
package;


import haxe.ui.Toolkit;
import haxe.ui.containers.dialogs.DialogButton;
import haxe.ui.core.Screen;
import openfl.display.*;
import openfl.display.Sprite;
import openfl.events.MouseEvent;


class Main extends Sprite {
	
	
	public function new () {
		
		super ();
		
		graphics.beginFill(0xffff00, 1);
		graphics.drawRect(0, 0, 300, 300);
		graphics.endFill();
		
		
		Toolkit.init();
		
		addEventListener(MouseEvent.CLICK, function (me:MouseEvent) {
			
			trace ("CLICK");
			
			Screen.instance.messageDialog("msg", "ttl", null, OnDlgBtn);
		});
		
	}
	
	private function OnDlgBtn(btn:DialogButton)
	{
		
	}
	
	
}
```

I might be misusing something, sorry for that
and if those are features in progress also good luck and looking forward

**Comment by ianharrigan** [comment]
Hi,

Yes, something is wrong here (with haxeui i think) - ill check it out.

Thanks!
