### ISSUE TITLE
haxeui-openfl broken for openfl v8

### ISSUE THREAD

**Issue by intoxopox** [haxeui/haxeui-openfl#24]
Can't build for neko, windows, or html targets once updated to OpenFL v8.0. Seems haxeui Component's invalidate is in conflict with OpenFL's invalidate method in DisplayObject.

**Comment by Igazine** [comment]
The problem is with DisplayObject.invalidate() which is a new function in OpenFL 8.0 but was previously defined in HaxeUI. So now the two has incompatible signature and parameters effectively making HaxeUI unusable in the new environment. Would be great if someone could come up with a solution

**Comment by ianharrigan** [comment]
from https://github.com/haxeui/haxeui-core/issues/223
> Hmmm, is this openfl 8? Thats kinda annoying, i guess we could rename all "invalidate*" functions to "invalidateComponent*" :(

Its annoying and ill get round to it asap, but i have other work commitments at the moment - maybe in a day or so.

**Comment by Igazine** [comment]
I'm experiencing very weird issues with layout container alignments, many things look off, not where they were originally placed.
That being said, I switched back to OpenFL 7.1.2 but kept the newest HaxeUI and suddenly everything compiles and works fine. There's something not OK with OpenFL 8, but that's another story. So far HaxeUI works and renders perfectly. OP should also post a follow up I think

Thank you for making the changes

**Comment by intoxopox** [comment]
I can build for all targets again, but have seen some buggy behavior with component size. I'll see if I can make a simple to test to isolate, as I can't tell if it's related to at all to this fix.

**Comment by ianharrigan** [comment]
Ok, an example would be great, openfl8 looks fine to me: 

![image](https://user-images.githubusercontent.com/3024242/40109024-c5137c02-58fc-11e8-94f7-3566d8b8ca2b.png)

Button text / size i think is a few pixels off to be fair, but nothing major (unless that what you meant?)

**Comment by FlashTang** [comment]
no luck , openfl 8.1.1 not works  
does haxeui-openfl works with starling-haxe ?

Called from ? line 1
Called from ApplicationMain.hx line 84
Called from ApplicationMain.hx line 116
Called from lime/app/Application.hx line 269
Called from lime/_backend/native/NativeApplication.hx line 160
Called from a C function
Called from lime/_backend/native/NativeApplication.hx line 453
Called from lime/_macros/EventMacro.hx line 101
Called from openfl/display/Stage.hx line 330
Called from openfl/display/Stage.hx line 924
Called from openfl/display/Stage.hx line 1014
Called from openfl/display/Stage.hx line 1285
Called from openfl/display/Stage.hx line 1010
Called from openfl/display/DisplayObject.hx line 453
Called from a C function
Called from openfl/events/EventDispatcher.hx line 217
Called from haxe/ui/backend/CallLaterBase.hx line 16
Called from haxe/ui/validation/ValidationManager.hx line 125
Called from haxe/ui/core/Component.hx line 1947
Called from haxe/ui/core/Component.hx line 1982
Called from haxe/ui/core/TextDisplay.hx line 235
Called from haxe/ui/core/TextDisplay.hx line 257
Called from haxe/ui/backend/TextDisplayBase.hx line 65
Called from /usr/local/lib/haxe/std/neko/_std/Std.hx line 39
Uncaught exception - std@math_floor

**Comment by FlashTang** [comment]
just crashs with blank openfl project  (non-starling object)

**Comment by FlashTang** [comment]
never mind , My fault !
It works now , I just forget to use Toolkit.init();
