### ISSUE TITLE
Button's repeater not working

### ISSUE THREAD

**Issue by intoxopox** [haxeui/haxeui-openfl#26]
## Expected Behavior
Setting button's repeater to true should cause click event to continue firing at intervals of repeaterInterval while button is pressed.

## Current Behavior
Setting button's repeater to true seems to have no effect at all.

**Comment by ianharrigan** [comment]
Which backend are you using? Do you have a minimal test case? I tried this on haxeui-html5:

```
<button text="Test" repeater="true" onclick="trace('bob')" />
```

And it all seems to work fine / as expected.

**Comment by ianharrigan** [comment]
This should be fixed now, can you retest and close if its all working? 

Cheers,
Ian
