### ISSUE TITLE
TextField and TextArea scroll page away when received focus

### ISSUE THREAD

**Issue by Helgiii** [haxeui/haxeui-openfl#27]
so my game is a frame inside another site..
and when I click on a textfield to input some data to customize game params inside game
the page scrolls down 
so It's pretty impossible to use at the moment. whenever you click inside textfields the page scrolls down and the textinput becomes not reachable((

**Comment by ianharrigan** [comment]
Hi,

Is it possible you have a small sample that display the problem? Im not 100% sure i understand what you mean.

Cheers,
Ian

**Comment by Helgiii** [comment]
ok I'll try making a sample app

**Comment by ianharrigan** [comment]
what does you html page look like (code wise), when i run the project i just get: 

![image](https://user-images.githubusercontent.com/3024242/42111124-9957aed0-7be3-11e8-88a6-b57d667cd971.png)

So presumably that live version is different. Just want to sync to understand it. 

Ian

**Comment by Helgiii** [comment]
ah yeah its in the attached zip file in the bin directory, bin/html5/bin
there are 2 files.. frame-container.html and index-game.html
index-game.html differes from original index.html that the IDE generates

**Comment by ianharrigan** [comment]
This seems to be an openfl issue: I replace all the code in your UiTest class with:

```
        var tf:TextField = new TextField();
        tf.type = TextFieldType.INPUT;
        tf.selectable = true;
        tf.mouseEnabled = true;
        tf.autoSize = TextFieldAutoSize.NONE;
        tf.multiline = true;
        tf.wordWrap = true;
        tf.text = "OpenFL TextField";
        Lib.current.stage.addChild(tf);
```

And the same thing occurs. That doesnt use HaxeUI anymore and just OpenFL. It might make sense to create an openfl only version of the issue and see if anyone on the forurms can help? i took a quick look to see if it was anything obvious and couldnt see much. I wonder if it is to do with only when using it in a frame, or using actuate? No sure. 

Ian

**Comment by Helgiii** [comment]
ok thanks! 
i'll add (copy) this issue to openfl page then
