### ISSUE TITLE
checkbox, optionbox cant be selected by label click on html5 platform

### ISSUE THREAD

**Issue by Helgiii** [haxeui/haxeui-openfl#29]
on flash it works ok
on html5 - not)
very inconvinient to click those small areas
thanx)

**Comment by intoxopox** [comment]
Work-around: Add a background-color, then set its background-opacity to 0.
`.checkbox {
	background-color: #ffffff;
	background-opacity: 0;
}`

**Comment by Helgiii** [comment]
tried this workaround - not working.
then I tried just
.checkbox { background-color: #ffffff;  }
the background appeared but was not clickable again, so i click the label of checkbox and checkbox's state is not changing

**Comment by ianharrigan** [comment]
It may be worth switching to new component, at least to see if you have any problems, obviously i dont know your application, but i doubt there would be any significant changes (events have moved, thats hopefully all i can think of off hand that may affect you), it is possible, however, that some apis are matched 1 -> 1, in which case i would love to know about them :)

let me know if i can help in someway,

Cheers,
Ian

**Comment by Helgiii** [comment]
I switched to new-component-method, it compiles but I get a runtime error in

Type$/createInstance at C:\HaxeToolkit\haxe\std\flash\_std\Type.hx:134
haxe.ui.core::Component/create at C:\HaxeToolkit\haxe\lib\haxeui-core\git\haxe\ui\core\Component.hx:105
haxe.ui.core::Component at C:\HaxeToolkit\haxe\lib\haxeui-core\git\haxe\ui\core\Component.hx:86
haxe.ui.components::Label at C:\HaxeToolkit\haxe\lib\haxeui-core\git\haxe\ui\components\Label.hx:12
...

[Fault] exception, information=ArgumentError: Error #1063: Argument count mismatch on haxe.ui.components._Label::Builder(). Expected 0, got 1.

**Comment by ianharrigan** [comment]
erm... thats strange - minimal test app? :)

**Comment by ianharrigan** [comment]
Also, what version of haxe?

**Comment by Helgiii** [comment]
oh looks like it was 	<haxeflag name="-dce" value="full" />
that caused that problem, I removed it and app ran ok (not tested it fully yet)

**Comment by ianharrigan** [comment]
hmmm... ok, thats good to know... that should work... so the new component method might needs some @:keeps or something. Let me know if that isnt the case. (Could you possibly open a new issue on haxeui-core if that is the case??)

Thanks!

**Comment by Helgiii** [comment]
this issue is fixed in the new-component-method branch
