### ISSUE TITLE
ScreenBase should not add to stage

### ISSUE THREAD

**Issue by MSGhero** [haxeui/haxeui-openfl#3]
`ScreenBase` should not be adding directly to the stage like [here](https://github.com/haxeui/haxeui-openfl/blob/master/haxe/ui/backend/ScreenBase.hx#L52). It would be better to add to a user-specified "container":

``` haxe
Toolkit.init( {
     container : myGame
} );
```

or something like that.

**Comment by ianharrigan** [comment]
This should be working now... Can you close if it works as you expect?

Cheers,
Ian

**Comment by MSGhero** [comment]
It'll have to wait until this weekend, but yes I will do that.

**Comment by MSGhero** [comment]
Haha maybe this weekend.

**Comment by MSGhero** [comment]
@ianharrigan I messaged you on slack. This probably works, but I can't test it out in flixel yet.

**Comment by ianharrigan** [comment]
https://github.com/haxeui/haxeui-core/issues/49

**Comment by ianharrigan** [comment]
^^ bump... can we close this if its no longer relevant / valid? 

Cheers.
