### ISSUE TITLE
Font's dont render by default due to lack of size: related to core issue 169

### ISSUE THREAD

**Issue by jrdoughty** [haxeui/haxeui-openfl#32]
The fix for https://github.com/haxeui/haxeui-core/issues/169 makes it so most elements don't have any font size by default
## Expected Behavior
Elements with text show on screen without explicitly stated font size:
![image](https://user-images.githubusercontent.com/3956893/50530072-08d9c980-0ac0-11e9-8986-c51508ad2465.png)

## Current Behavior
if font size isn't stated, elements shrink and font's aren't visible
![image](https://user-images.githubusercontent.com/3956893/50530048-cb753c00-0abf-11e9-86a9-98e0be8bd4c1.png)

If you need more info or can't reproduce, let me know and I'll make a stripped down app to show what I've got

**Comment by ianharrigan** [comment]
I would always love a stripped down app... it makes it much easier to test... Something is defo off there

Cheers,
Ian

**Comment by ianharrigan** [comment]
Out of interest, does the same apply to the "new component method" branch(es)?

**Comment by jrdoughty** [comment]
Got this when I switched branches:
C:/HaxeToolkit/haxe/lib/haxeui-openfl/git/haxe/ui/backend/ScreenBase.hx:188: characters 17-35 : haxe.ui.core.MouseEvent has no field ctrlKey
C:/HaxeToolkit/haxe/lib/haxeui-openfl/git/haxe/ui/backend/ScreenBase.hx:189: characters 17-36 : haxe.ui.core.MouseEvent has no field shiftKey
C:/HaxeToolkit/haxe/lib/haxeui-openfl/git/haxe/ui/backend/ScreenBase.hx:203: characters 17-38 : haxe.ui.core.KeyboardEvent has no field ctrlKey
C:/HaxeToolkit/haxe/lib/haxeui-openfl/git/haxe/ui/backend/ComponentBase.hx:290: characters 17-35 : haxe.ui.core.MouseEvent has no field ctrlKey
C:/HaxeToolkit/haxe/lib/haxeui-openfl/git/haxe/ui/backend/ComponentBase.hx:291: characters 17-36 : haxe.ui.core.MouseEvent has no field shiftKey
C:/HaxeToolkit/haxe/lib/haxeui-core/git/haxe/ui/core/Screen.hx:270: characters 13-29 : haxe.ui.backend.ScreenBase has no field hideDialog
C:/HaxeToolkit/haxe/lib/haxeui-core/git/haxe/ui/core/Screen.hx:269: lines 269-299 : Field hideDialog is declared 'override' but doesn't override any field
C:/HaxeToolkit/haxe/lib/haxeui-core/git/haxe/ui/core/Screen.hx:97: characters 22-41 : haxe.ui.backend.ScreenBase has no field messageDialog
C:/HaxeToolkit/haxe/lib/haxeui-core/git/haxe/ui/core/Screen.hx:145: characters 22-38 : haxe.ui.backend.ScreenBase has no field showDialog
C:/HaxeToolkit/haxe/lib/haxeui-core/git/haxe/ui/core/Screen.hx:144: lines 144-188 : Field showDialog is declared 'override' but doesn't override any field
C:/HaxeToolkit/haxe/lib/haxeui-core/git/haxe/ui/core/Screen.hx:96: lines 96-142 : Field messageDialog is declared 'override' but doesn't override any field
Build halted with errors.
Done(1)
C:\HaxeToolkit\haxe\lib\haxeui-openfl\git\haxe\ui\backend\ComponentBase.hx:290: chars 16-34 : Error: haxe.ui.core.MouseEvent has no field ctrlKey
C:\HaxeToolkit\haxe\lib\haxeui-openfl\git\haxe\ui\backend\ComponentBase.hx:291: chars 16-35 : Error: haxe.ui.core.MouseEvent has no field shiftKey
C:\HaxeToolkit\haxe\lib\haxeui-openfl\git\haxe\ui\backend\ComponentBase.hx:15: chars 0-41 : Warning: Unused import

**Comment by ianharrigan** [comment]
you'll need `new-component-method` branch of `haxeui-core` _and_ `haxeui-openfl`

**Comment by jrdoughty** [comment]
Ah, gotcha, I'll try that momentarily, heres the mini app:
https://github.com/jrdoughty/mini-haxe-ui-app

**Comment by jrdoughty** [comment]
This appears to be fixed in the new component method at present
