### ISSUE TITLE
[new-component-method] TextArea bug on receiving focus (just msclick it to test), flash target

### ISSUE THREAD

**Issue by Helgiii** [haxeui/haxeui-openfl#36]
[Fault] exception, information=TypeError: Error #1034: Type Coercion failed: cannot convert haxe.ui.events::FocusEvent@68a5511 to haxe.ui.events.MouseEvent.

**Comment by ianharrigan** [comment]
This should be fixed now (finally!)

**Comment by Helgiii** [comment]
the bug is back again
