### ISSUE TITLE
[new-component-method] scrollbox (or grid) performance degraded.. lags, works slower now

### ISSUE THREAD

**Issue by Helgiii** [haxeui/haxeui-openfl#38]
so basically I have a user ratings chart implemented as a vertical 2 column grid inside a scrollbox
and in new-component-method branch it started to lag.. so I grab the scrollbtn move it and scrolling lags.
html5 target

**Comment by ianharrigan** [comment]
Is there a reproducible example?

**Comment by Helgiii** [comment]
I'll make one today\tomorrow :)

**Comment by ianharrigan** [comment]
Fix for this is done (Math.fround in handleClipRect) - will leave this open till my current checkout is commited, but confirmed as fixed
