### ISSUE TITLE
Placeholder text doesn't clear in text fields on receiving focus

### ISSUE THREAD

**Issue by jrdoughty** [haxeui/haxeui-openfl#42]
## Expected Behavior
clicking on the text field would clear out the placeholder text

## Current Behavior
clicking on the text field puts the cursor at the end of the placeholder text, and the text remains there

## Test app / minimal test case
https://github.com/jrdoughty/mini-haxe-ui-app/tree/master/tabbing-openfl

## Your Environment
From haxelib list:
actuate: [1.8.9]
flixel: 4.6.1 [4.6.2]
haxeui-core: 0.0.4 [git]
haxeui-openfl: [git]
haxeui: [1.8.21]
hscript: [2.3.0]
hxcpp: [4.0.8] 4.0.19
hxjsonast: [1.0.1]
json2object: [3.6.3]
lime: 2.9.1 [7.3.0] 7.5.0
openfl: 3.6.1 [8.9.0] 8.9.1
test-adapter: 1.2.1 [dev:c:\Users\jdoughty\.vscode\extensions\vshaxe.haxe-test-adapter-1.2.3\test-adapter]

**Comment by ianharrigan** [comment]
Just to check are you using new-component-method branch?

**Comment by jrdoughty** [comment]
Sorry, yes I am. Should have mentioned that in the bug

**Comment by ianharrigan** [comment]
Cool - no worries, just making sure

**Comment by ianharrigan** [comment]
If you PR fixes this issue - feel free to close (i generally dont like to close issues i didnt create)

**Comment by jrdoughty** [comment]
Absolutely :)
