### ISSUE TITLE
[HTML5] Performance lost

### ISSUE THREAD

**Issue by flashultra** [haxeui/haxeui-openfl#46]
When I use haxeui with openfl and target HTML5  have performance lost ( from 60 fps to 20-25 fps) 
Here are two screen records  for html5 and flash version ( fps is visible on the top left side )
**1) HTML5 version**
![haxeui-html5](https://user-images.githubusercontent.com/13473027/69011360-4c585300-0972-11ea-94bd-36416830c366.gif)

**2) Flash version**
![haxeui-flash](https://user-images.githubusercontent.com/13473027/69011365-55492480-0972-11ea-9442-cd1d005e7896.gif)

Here is the sample project:   https://drive.google.com/file/d/1dU1pZnuDigtWAuxgu0jDlbq7rumU9_ly/view?usp=sharing

**Comment by ianharrigan** [comment]
Hmmm - thats annoying!

When i run the app i dont get any perf issues. Makes it pretty hard to debug :/

![perf](https://user-images.githubusercontent.com/3024242/69012288-6a26b780-0974-11ea-90f4-29e00736cd96.gif)

**Comment by flashultra** [comment]
Strange. You can try on Firefox ( it's worse than Chrome) . Also at the moment have 25 elements in the list  which maybe is not enough .
 My laptop is  
 Intel Core i5-4300M CPU @ 2.60GHz
 Intel HD Graphics 4600 with   Driver version  20.19.15.4549 ( 11/10/2016 ) (latest available)
Testing with git version on haxeui-core and haxeui-openfl.

Also using Openfl  8.9.5   and Lime  7.6.3

**Comment by flashultra** [comment]
@ianharrigan  you can try compile html5 version here : https://bgsvara.com/hx/
I think maybe my latest version ( Openfl 8.9.5 and Lime 7.6.3 ) could be the problem.

**Comment by ianharrigan** [comment]
![perf2](https://user-images.githubusercontent.com/3024242/69144507-be907b00-0acb-11ea-9a4e-351093647d9e.gif)

Feels more fluid than the last - was it supposed to be slow? 

(ps: noticed you are missing some haxeui stock images also, like the arrows for the scrolls - nothing to do with this, but just something i noticed)

**Comment by flashultra** [comment]
Yes, it should be slow that before.
Very strange. Could I ask what graphic card you use ( and how old is the driver) ?
 I suppose you test under windows ( not linux or mac )  ?

I just tried to switch off opengl support ( using ```<window allowHighDPI="true" hardware="false" allow-shaders="false" require-shaders="false" depth-buffer="false" stencil-buffer="false"/>``` )  and performance is much  better ( https://bgsvara.com/nohx/ ) .

So maybe the problem is with openfl ( and OpenGL under Windows 10 )

**Comment by ianharrigan** [comment]
"nohx" seems just as good. How is nohx for you?

dxdiag is:

![image](https://user-images.githubusercontent.com/3024242/69163382-6323b480-0aee-11ea-8281-cb430fd35a8c.png)

![image](https://user-images.githubusercontent.com/3024242/69163405-6cad1c80-0aee-11ea-86a9-9cc3e165f4c8.png)

**Comment by flashultra** [comment]
nohx is solid 61 fps for me, but this is only CPU render , not OpenGL.
 Still wondering what cause the problem. Maybe 2 GB VRam is not enough for OpenGL ( this is on my laptop)
![dxdiag](https://user-images.githubusercontent.com/13473027/69165438-42615c00-0afa-11ea-9481-20c80fb63a1d.png)
