### ISSUE TITLE
option and check boxes dont get scrolled ok in a scrollview

### ISSUE THREAD

**Issue by Helgiii** [haxeui/haxeui-openfl#49]
so you scroll down/up a scrollview
btns, lbls, images are fine
and option\check boxes appear frozen (dont move)
if you hover mouse over the places where they actually should be, they get redrawn

**Comment by ianharrigan** [comment]
What version of openfl? i think this is an issue with openfl and shadows... ive seen something _similar_ before (assuming im understanding what you mean)

**Comment by Helgiii** [comment]
openfl 8,9,6
haxeui-core 1,0,21
haxeui-openfl 1.0.6

**Comment by ianharrigan** [comment]
not sure best way to go here, maybe remove the shadows for now? Though in 8.9.5 i think its working... so i wonder if it will be fixed again in a new release... not sure...

**Comment by Helgiii** [comment]
Thanx for the tip! I turned off the shadows (found "checkboxes.css", "optionboxes.css" files in the haxeui-core folder and set filter:none;). Now they are scrolled fine:)
I also noticed that chk\option boxes no longer get selected when their associated label is clicked.

**Comment by ianharrigan** [comment]
OK, cool - ill think about whether to remove them core or not, maybe it just makes sense to for now (for openfl only)... fyi, you dont need to edit haxeui core, you could just add a stylesheet into your app with:

```
.optionbox, .checkbox { 
    filter: none;
}
```

Did the checkboxes used to be selectable by their label? Do they have background? Openfl wont issue mouse events for transparent sprites

**Comment by intoxopox** [comment]
Just thought I'd chime in to say that openfl filters are largely off (or at least unreliable) until openfl v9.... even in openfl dev branch. There's a separate v9 dev branch.
