### ISSUE TITLE
Android app going out of the screen

### ISSUE THREAD

**Issue by WSandwitch** [haxeui/haxeui-openfl#56]
## Expected Behavior
neko window looks like andriod window

## Current Behavior
android contents going out of screen

## Media

![Снимок экрана_2021-06-28_15-45-03_](https://user-images.githubusercontent.com/7642532/123639955-59654580-d829-11eb-950a-57efe30fdf1f.png)

## Your Environment

* Version used: openfl: [9.1.0] haxeui-core: [1.2.3] haxeui-openfl: [1.2.3]
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop or mobile): android 11, android 8, ubuntu 20.04(neko)
* Link to your project: https://github.com/WSandwitch/Inventory

**Comment by ianharrigan** [comment]
Can you retry with latest git version of haxeui-core and haxeui-openfl? Also, if it doesnt work, can you trace out "Screen.instance.width", "Screen.instance.height", "Screen.instance.dpi" and "Toolkit.scale"

Cheers,
Ian

**Comment by WSandwitch** [comment]
Last git versions work fine.
Thanks.

**Comment by ianharrigan** [comment]
Great! Ill try and get a release asap!
