### ISSUE TITLE
Tableview in DOM

### ISSUE THREAD

**Issue by hoseyjoe** [haxeui/haxeui-openfl#7]
Compiling to Openfl with application.xml tag <haxedef name="dom" /> causes scrollbar to not work

This is probably an openfl issue.  But not sure what ticket to make for it

Scroll1.jpg is before scrolling.  Scroll2 is after scrolling a bit.  You notice the line highlights moves down but the text stays in place.

![scroll1](https://cloud.githubusercontent.com/assets/2074385/20506977/c46129c0-b00c-11e6-89dc-be5fe0f22177.jpg)
![scroll2](https://cloud.githubusercontent.com/assets/2074385/20506978/c461bc1e-b00c-11e6-8163-76f0d2d1bcff.jpg)

minimal test case
[TableTest.zip](https://github.com/haxeui/haxeui-openfl/files/605182/TableTest.zip)

**Comment by ianharrigan** [comment]
Is this compiling to openfl using dom?

**Comment by hoseyjoe** [comment]
yes. that is correct. Sorry, the first sentence was supposed to be:

Compiling to Openfl with application.xml tag **DOM** causes scrollbar to not work

**Comment by ianharrigan** [comment]
Can we retest this with latest openfl? I believe some recent dom changes have fixed this.

**Comment by hoseyjoe** [comment]
I am making bug for them and will test when it is resolved.  I am now getting

`cmd: "C:\sdks\haxe3\haxe/haxelib" run lime build "application.xml" html5 -debug -Dfdb
C:/sdks/haxe3/haxe/lib/openfl/4,5,1/openfl/display/OpenGLView.hx:41: characters 3-11 : Unknown identifier : __canvas
C:/sdks/haxe3/haxe/lib/openfl/4,5,1/openfl/display/OpenGLView.hx:42: characters 3-11 : Unknown identifier : __canvas
C:/sdks/haxe3/haxe/lib/openfl/4,5,1/openfl/display/OpenGLView.hx:43: characters 3-11 : Unknown identifier : __canvas
C:/sdks/haxe3/haxe/lib/openfl/4,5,1/openfl/display/OpenGLView.hx:58: characters 3-12 : Unknown identifier : __context
C:/sdks/haxe3/haxe/lib/openfl/4,5,1/openfl/display/OpenGLView.hx:64: characters 21-30 : Unknown identifier : __context
C:/sdks/haxe3/haxe/lib/openfl/4,5,1/openfl/display/OpenGLView.hx:261: characters 2-10 : Unknown identifier : __canvas
C:/sdks/haxe3/haxe/lib/openfl/4,5,1/openfl/display/OpenGLView.hx:271: characters 2-10 : Unknown identifier : __canvas`

**Comment by ianharrigan** [comment]
Thats not dom by the looks of it...  `OpenGLView.hx`

**Comment by hoseyjoe** [comment]
Ya, I know.  i hacked openfl to allow it through and it fixes the issue with compile.  And once compiled this issue, as described no longer appears.
